export enum ImageNames {
  Circle = "circle",
  GrassTile = "grasstile",
  DirtTile = "dirttile",
  Pole = "pole",
  PoleTop = "poletop",
  Cloud = 'cloud',
  Arrow = 'arrow',
  Girl = "girl",
  IdleGirl = "idlegirl",
  RunningGirl = "runninggirl",
  Monster = "monster",
  IdleMonster = "idlemonster",
  RunningMonster = "runningmonster",
}
